src/Metrc.SampleProject.WebApp/Models/ErrorViewModel.cs
using System;

namespace Metrc.SampleProject.WebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/Metrc.SampleProject.WebApp/Models/MemberPlanetsModel.cs
using System;

namespace Metrc.SampleProject.WebApp.Models
{
    public class MemberPlanetsModel
    {
        public Boolean UpdateModal { get; set; }

        public Int64 Id { get; set; }
        public String Name { get; set; }
        public Int32 xcoordinates { get; set; }
        public Int32 ycoordinates { get; set; }
        public Int32 zcoordinates { get; set; }
    }
}

src/Metrc.SampleProject.WebApp/Models/ShipInfoModel.cs
using System;

namespace Metrc.SampleProject.WebApp.Models
{
    public class ShipInfoModel
    {
        public Boolean UpdateModal { get; set; }

        public Int64 Id { get; set; }
        public String Name { get; set; }
        public Int64 Occupancy { get; set; }
        public String Status { get; set; }
        public Int64 ShipTypeId { get; set; }
    }
}

src/Metrc.SampleProject.WebApp/Models/ShipTypeModel.cs
using System;

namespace Metrc.SampleProject.WebApp.Models
{
    public class ShipTypeModel
    {
        public Boolean UpdateModal { get; set; }

        public Int64 Id { get; set; }
        public String Name { get; set; }
        public Double TopSpeed { get; set; }
    }
}

src/Metrc.SampleProject.WebApp/Controllers/DeploymentController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Diagnostics;
using System.Text;
using Metrc.SampleProject.Deployments;

namespace Metrc.SampleProject.WebApp.Controllers
{
    [Route("[controller]")]
    [Controller]
    public partial class DeploymentController : Controller
    {
        [HttpGet("Migrate")]
        public virtual IActionResult Migrate()
        {
            var result = new StringBuilder();

            result.AppendFormat("Deployment Migrate:{0}{0}", Environment.NewLine);
            result.AppendFormat("Deployment Started at {0}{1}", DateTime.Now, Environment.NewLine);

            var stopwatch = Stopwatch.StartNew();
            Deployment.MigrateDatabase(Startup.ConnectionString);
            result.AppendFormat("Deployment Completed in {0:N0} ms{1}", stopwatch.ElapsedMilliseconds, Environment.NewLine);

            result.AppendFormat("Deployment Ended at {0}{1}", DateTime.Now, Environment.NewLine);

            return Content(result.ToString());
        }

        [HttpGet("Clean")]
        public virtual IActionResult Clean()
        {
            var result = new StringBuilder();

            result.AppendFormat("Deployment Clean:{0}{0}", Environment.NewLine);
            result.AppendFormat("Deployment Started at {0}{1}", DateTime.Now, Environment.NewLine);

            var stopwatch = Stopwatch.StartNew();
            Deployment.CleanDatabase(Startup.ConnectionString);
            Deployment.MigrateDatabase(Startup.ConnectionString);
            result.AppendFormat("Deployment Completed in {0:N0} ms{1}", stopwatch.ElapsedMilliseconds, Environment.NewLine);

            result.AppendFormat("Deployment Ended at {0}{1}", DateTime.Now, Environment.NewLine);

            return Content(result.ToString());
        }

    }
}

src/Metrc.SampleProject.WebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Metrc.SampleProject.WebApp.Models;

namespace Metrc.SampleProject.WebApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Welcome to the First Galactic Empire.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/Metrc.SampleProject.WebApp/Controllers/MemberPlanetsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using Metrc.SampleProject.Services.Infrastructure;
using Metrc.SampleProject.Services.MemberPlanets;
using Metrc.SampleProject.WebApp.Models;

namespace Metrc.SampleProject.WebApp.Controllers
{
    public class MemberPlanetsController : Controller
    {
        private MemberPlanetsRepository _MemberPlanetsRepository;

        public MemberPlanetsController()
        {
            _MemberPlanetsRepository = Repositories.MemberPlanetsRepository;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AddEdit(Int64? id = null)
        {
            var model = new MemberPlanetsModel
            {
                UpdateModal = id.HasValue
            };

            if (id.HasValue)
            {
                var memberPlanet = _MemberPlanetsRepository.GetMemberPlanetsById(id.Value);

                model.Id = memberPlanet.Id;
                model.Name = memberPlanet.Name;
                model.xcoordinates = memberPlanet.Xcoordinates;
                model.ycoordinates = memberPlanet.Ycoordinates;
                model.zcoordinates = memberPlanet.Zcoordinates;
            }

            return View(model);
        }
    }
}

src/Metrc.SampleProject.WebApp/Controllers/ShipInfoController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using Metrc.SampleProject.Services.Infrastructure;
using Metrc.SampleProject.Services.ShipInfo;
using Metrc.SampleProject.WebApp.Models;

namespace Metrc.SampleProject.WebApp.Controllers
{
    public class ShipInfoController : Controller
    {
        private ShipInfoRepository _ShipInfoRepository;

        public ShipInfoController()
        {
            _ShipInfoRepository = Repositories.ShipInfoRepository;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AddEdit(Int64? id = null)
        {
            var model = new ShipInfoModel
            {
                UpdateModal = id.HasValue
            };

            if (id.HasValue)
            {
                var shipInfo = _ShipInfoRepository.GetShipInfoById(id.Value);

                model.Id = shipInfo.Id;
                model.Name = shipInfo.Name;
                model.Occupancy = shipInfo.Occupancy;
                model.Status = shipInfo.Status;
                model.ShipTypeId = shipInfo.ShipTypeId;
            }

            return View(model);
        }
    }
}

src/Metrc.SampleProject.WebApp/Controllers/ShipTypeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using Metrc.SampleProject.Services.Infrastructure;
using Metrc.SampleProject.Services.ShipType;
using Metrc.SampleProject.WebApp.Models;

namespace Metrc.SampleProject.WebApp.Controllers
{
    public class ShipTypeController : Controller
    {
        private ShipTypeRepository _ShipTypeRepository;

        public ShipTypeController()
        {
            _ShipTypeRepository = Repositories.ShipTypeRepository;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AddEdit(Int64? id = null)
        {
            var model = new ShipTypeModel
            {
                UpdateModal = id.HasValue
            };

            if (id.HasValue)
            {
                var shipType = _ShipTypeRepository.GetShipTypeById(id.Value);

                model.Id = shipType.Id;
                model.Name = shipType.Name;
                model.TopSpeed = shipType.TopSpeed;
            }

            return View(model);
        }
    }
}

src/Metrc.SampleProject.WebApp/Views/Home/About.cshtml
@{
	ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>This application is designed to test new recruits to to the First Galactic Empire, Software Engineering division.</p>

<br />

<p>Click <a asp-area="" asp-controller="Home" asp-action="Privacy">here</a> to view the privacy policy</p>
<p>Click <a asp-area="" asp-controller="Deployment" asp-action="Migrate">here</a> to run migrations</p>
<p>Click <a asp-area="" asp-controller="Deployment" asp-action="Clean">here</a> to clean migrations</p>



src/Metrc.SampleProject.WebApp/Views/Home/Index.cshtml
@{
	ViewData["Title"] = "Home Page";
}

<h1>Welcome to the Imperial Archives</h1>

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
	<ol class="carousel-indicators">
		<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
		<li data-target="#myCarousel" data-slide-to="1"></li>
		<li data-target="#myCarousel" data-slide-to="2"></li>
	</ol>
	<div class="carousel-inner" role="listbox">
		<div class="item active">
			<img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
			<div class="carousel-caption" role="option">
				<p>
					Learn how to build ASP.NET apps that can run anywhere.
					<a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
						Learn More
					</a>
				</p>
			</div>
		</div>
		<div class="item">
			<img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
			<div class="carousel-caption" role="option">
				<p>
					There are powerful new features in Visual Studio for building modern web apps.
					<a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
						Learn More
					</a>
				</p>
			</div>
		</div>
		<div class="item">
			<img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
			<div class="carousel-caption" role="option">
				<p>
					Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
					<a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
						Learn More
					</a>
				</p>
			</div>
		</div>
	</div>
	<a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
		<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
		<span class="sr-only">Previous</span>
	</a>
	<a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
		<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
		<span class="sr-only">Next</span>
	</a>
</div>

<div class="row">
	<div class="col-md-3">
		<h2>Application uses</h2>
		<ul>
			<li>Sample pages using ASP.NET Core MVC</li>
			<li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
		</ul>
	</div>
	<div class="col-md-3">
		<h2>How to</h2>
		<ul>
			<li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
			<li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
			<li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
			<li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
			<li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
		</ul>
	</div>
	<div class="col-md-3">
		<h2>Overview</h2>
		<ul>
			<li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
			<li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
			<li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
			<li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
			<li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
			<li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
			<li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
		</ul>
	</div>
	<div class="col-md-3">
		<h2>Run &amp; Deploy</h2>
		<ul>
			<li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
			<li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
			<li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
		</ul>
	</div>
</div>

src/Metrc.SampleProject.WebApp/Views/MemberPlanets/AddEdit.cshtml
@model MemberPlanetsModel

<form>
	<input name="model[Id]" type="hidden" value="@Model.Id" />
	<div class="control-group">
		<label class="control-label">Name</label>
		<div class="controls">
			<input class="validate[required]" name="model[Name]" type="text" value="@Model.Name" />
		</div>
	</div>
	<br />
	<div class="control-group">
		<label class="control-label">X Coordinates</label>
		<div class="controls">
			<input class="validate[required]" name="model[xcoordinates]" required type="number" value="@Model.xcoordinates" />
		</div>
	</div>
	<br />
	<div class="control-group">
		<label class="control-label">Y Coordinates</label>
		<div class="controls">
			<input class="validate[required]" name="model[ycoordinates]" required type="number" value="@Model.ycoordinates" />
		</div>
	</div>
	<br />
	<div class="control-group">
		<label class="control-label">Z Coordinates</label>
		<div class="controls">
			<input class="validate[required]" name="model[zcoordinates]" required type="number" value="@Model.zcoordinates" />
		</div>
	</div>
	<br />
	<div class="form-actions">
		<button class="btn btn-success shadow" type="submit">@(Model.UpdateModal ? "Update" : "Create") Member Planet</button>
		<button id="cancel" class="btn shadow" type="button">Cancel</button>
	</div>
</form>

src/Metrc.SampleProject.WebApp/Views/MemberPlanets/Index.cshtml
@{
	ViewData["Title"] = "Member Planets";
}

<h2>Member Planets</h2>
<br />
<div class="btn-toolbar">
	<div class="btn-group">
		<button id="addmemberplanet-btn" class="btn shadow" type="button">Add Member Planet</button>
		<button id="updatememberplanet-btn" class="btn shadow" type="button">Update Member Planet</button>
		<button id="archivememberplanet-btn" class="btn shadow" type="button">Archive Member Planet</button>
	</div>
</div>
<div id="memberplanets-grid"></div>

@section Scripts {
	<script>
		(function () {
			let $memberPlantsGrid = $('#memberplanets-grid');

			var memberPlantsDataSource = metrc.kendo.serverDataSource({
				url: '@Url.Action("Get", "MemberPlanetsApi")'
			});

			$memberPlantsGrid.kendoGrid({
				dataSource: memberPlantsDataSource,
				selectable: true,
				columns: [
					{
						title: 'Planet Name', field: 'Name'
					},
					{
						title: 'Location', field: 'Location',
						template: 'X: #= Xcoordinates # Y: #= Ycoordinates # Z: #= Zcoordinates #'
					}
				]
			});
			memberPlantsDataSource.read();

			$('#addmemberplanet-btn').click(function() {
				metrc.kendo.modalWindow(
					'Add Member Planet',
					'@Url.Action("AddEdit", "MemberPlanets")',
					{
						isModal: true
					},
					null,
					'@Url.Action("CreateMemberPlanet", "MemberPlanetsApi")',
					$memberPlantsGrid);
			});

			$('#updatememberplanet-btn').click(function () {
				let selectedId = $memberPlantsGrid.metrcGridIds('Id');

				if (!selectedId || selectedId <= 0) {
					alert("Please select an item to update");
					return;
				}

				metrc.kendo.modalWindow(
					'Update Member Planet',
					'@Url.Action("AddEdit", "MemberPlanets")',
					{
						isModal: true,
						id: selectedId
					},
					null,
					'@Url.Action("UpdateMemberPlanet", "MemberPlanetsApi")',
					$memberPlantsGrid);
			});

			$('#archivememberplanet-btn').click(function () {
				let selectedId = $memberPlantsGrid.metrcGridIds('Id');

				if (!selectedId || selectedId <= 0) {
					alert("Please select an item to archive");
					return;
				}

				if (!confirm("Are you sure you want to remove this member planet?")) {
					return;
				}

				metrc.submitJson({
					url: '@Url.Action("ArchiveMemberPlanet", "MemberPlanetsApi")',
					data: { Id: selectedId[0] },
					success: function () {
						memberPlantsDataSource.read();
					}
				});
			});
		})();
	</script>
}

src/Metrc.SampleProject.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Metrc Sample Project</title>

	<environment include="Development">
		<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
		<link rel="stylesheet" href="~/css/site.css" />
		<link rel="stylesheet" href="https://kendo.cdn.telerik.com/2021.1.224/styles/kendo.common.min.css">
		<link rel="stylesheet" href="https://kendo.cdn.telerik.com/2021.1.224/styles/kendo.default.min.css">
	</environment>
	<environment exclude="Development">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
			  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
			  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
		<link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
	</environment>
</head>
<body>
	<nav class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Metrc Sample Project</a>
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
					<li><a asp-area="" asp-controller="MemberPlanets" asp-action="Index">Member Planets</a></li>
					<li><a asp-area="" asp-controller="ShipType" asp-action="Index">Ship Type</a></li>
					<li><a asp-area="" asp-controller="ShipInfo" asp-action="Index">Ship Info</a></li>
					<li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
				</ul>
			</div>
		</div>
	</nav>
	<div id="user-alerts" class="shadow"></div>

	<div class="container body-content">
		@RenderBody()
		<hr />
		<footer>
			<p>&copy; 2019 - Metrc Sample Project</p>
		</footer>
	</div>

	<environment include="Development">
		<script src="~/lib/jquery/dist/jquery.js"></script>
		<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
		<script src="~/js/site.js" asp-append-version="true"></script>
		<script src="https://kendo.cdn.telerik.com/2021.1.224/js/kendo.all.min.js"></script>
		<script src="~/lib/spin.min.js"></script>
		<script src="~/lib/jquery.serialize-object.compiled.js"></script>
	</environment>
	<environment exclude="Development">
		<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
				asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
				asp-fallback-test="window.jQuery"
				crossorigin="anonymous"
				integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
		</script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
				asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
				asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
				crossorigin="anonymous"
				integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
		</script>
		<script src="~/js/site.min.js" asp-append-version="true"></script>
	</environment>

	@RenderSection("Scripts", required: false)
</body>
</html>

src/Metrc.SampleProject.WebApp/Views/Shared/_Modal.cshtml
@RenderBody()
@RenderSection("Scripts", required: false)

src/Metrc.SampleProject.WebApp/Views/ShipInfo/Index.cshtml
@{
	ViewData["Title"] = "Ship Info";
}

<h2>Ship Info</h2>
<br />
<div class="btn-toolbar">
	<div class="btn-group">
        <button id="addshipinfo-btn" class="btn shadow" type="button">Add Ship Info</button>
        <button id="updateshipinfo-btn" class="btn shadow" type="button">Update Ship Info</button>
        <button id="archiveshipinfo-btn" class="btn shadow" type="button">Archive Ship Info</button>
	</div>
</div>
<div id="shipinfo-grid"></div>

@section Scripts {
    <script>
		var shipTypeNames = new Map();
		(function () {
            let $shipInfoGrid = $('#shipinfo-grid');

            const shipInfoDataSource = metrc.kendo.serverDataSource({
				url: '@Url.Action("Get", "ShipInfoApi")'
            });
            shipInfoDataSource.read();
			const shipTypeDataSource = metrc.kendo.serverDataSource({
				url: '@Url.Action("Get", "ShipTypeApi")'
            });
			shipTypeDataSource.read();

			shipTypeDataSource.fetch(() => {
				const view = shipTypeDataSource.view();
				shipTypeNames = new Map(view.map(x => [x.Id, x.Name]))
                $shipInfoGrid.kendoGrid({
                    dataSource: shipInfoDataSource,
                    selectable: true,
                    columns: [
                        {
                            title: 'Ship Info', field: 'Name'
                        },
                        {
                            title: 'Occupancy', field: 'Occupancy'
                        },
                        {
                            title: 'Status', field: 'Status'
                        },
                        {
                            title: 'Ship Type', template: '#= shipTypeNames.get(data.ShipTypeId) #'
                        }
                    ]
                });
			});

            $('#addshipinfo-btn').click(function() {
				metrc.kendo.modalWindow(
					'Add Ship Info',
					'@Url.Action("AddEdit", "ShipInfo")',
					{
						isModal: true
					},
					null,
					'@Url.Action("CreateShipInfo", "ShipInfoApi")',
					$shipInfoGrid,
					null,
					() => {
                        $('.shiptypedropdown').kendoDropDownList({
                            dataTextField: 'Name',
                            dataValueField: 'Id',
                            dataSource: shipTypeDataSource
                        });
                    }
				);
			});

            $('#updateshipinfo-btn').click(function () {
                let selectedId = $shipInfoGrid.metrcGridIds('Id');

				if (!selectedId || selectedId <= 0) {
					alert("Please select an item to update");
					return;
				}

				metrc.kendo.modalWindow(
					'Update Ship Info',
					'@Url.Action("AddEdit", "ShipInfo")',
					{
						isModal: true,
						id: selectedId
					},
					null,
					'@Url.Action("UpdateShipInfo", "ShipInfoApi")',
                    $shipInfoGrid,
                    null,
                    () => {
                        $('.shiptypedropdown').kendoDropDownList({
                            dataTextField: 'Name',
							dataValueField: 'Id',
                            dataSource: shipTypeDataSource
                        });
					}
				);
			});

            $('#archiveshipinfo-btn').click(function () {
                let selectedId = $shipInfoGrid.metrcGridIds('Id');

				if (!selectedId || selectedId <= 0) {
					alert("Please select an item to archive");
					return;
				}

				if (!confirm("Are you sure you want to remove this ship info?")) {
					return;
				}

				metrc.submitJson({
					url: '@Url.Action("ArchiveShipInfo", "ShipInfoApi")',
					data: { Id: selectedId[0] },
					success: function () {
						shipInfoDataSource.read();
					}
				});
			});
		})();
    </script>
}

src/Metrc.SampleProject.WebApp/Views/ShipType/Index.cshtml
@{
	ViewData["Title"] = "Ship Type";
}

<h2>Ship Type</h2>
<br />
<div class="btn-toolbar">
	<div class="btn-group">
		<button id="addshiptype-btn" class="btn shadow" type="button">Add Ship Type</button>
		<button id="updateshiptype-btn" class="btn shadow" type="button">Update Ship Type</button>
		<button id="archiveshiptype-btn" class="btn shadow" type="button">Archive Ship Type</button>
	</div>
</div>
<div id="shiptype-grid"></div>

@section Scripts {
	<script>
		(function () {
			let $shipTypeGrid = $('#shiptype-grid');

			var shipTypeDataSource = metrc.kendo.serverDataSource({
				url: '@Url.Action("Get", "ShipTypeApi")'
			});

			$shipTypeGrid.kendoGrid({
				dataSource: shipTypeDataSource,
				selectable: true,
				columns: [
					{
						title: 'Ship Type', field: 'Name'
					},
					{
						title: 'Top Speed (X light speed)', field: 'TopSpeed'
					}
				]
			});
			shipTypeDataSource.read();

			$('#addshiptype-btn').click(function() {
				metrc.kendo.modalWindow(
					'Add Ship Type',
					'@Url.Action("AddEdit", "ShipType")',
					{
						isModal: true
					},
					null,
					'@Url.Action("CreateShipType", "ShipTypeApi")',
					$shipTypeGrid);
			});

			$('#updateshiptype-btn').click(function () {
				let selectedId = $shipTypeGrid.metrcGridIds('Id');

				if (!selectedId || selectedId <= 0) {
					alert("Please select an item to update");
					return;
				}

				metrc.kendo.modalWindow(
					'Update Ship Type',
					'@Url.Action("AddEdit", "ShipType")',
					{
						isModal: true,
						id: selectedId
					},
					null,
					'@Url.Action("UpdateShipType", "ShipTypeApi")',
					$shipTypeGrid);
			});

			$('#archiveshiptype-btn').click(function () {
				let selectedId = $shipTypeGrid.metrcGridIds('Id');

				if (!selectedId || selectedId <= 0) {
					alert("Please select an item to archive");
					return;
				}

				if (!confirm("Are you sure you want to remove this ship type?")) {
					return;
				}

				metrc.submitJson({
					url: '@Url.Action("ArchiveShipType", "ShipTypeApi")',
					data: { Id: selectedId[0] },
					success: function () {
						shipTypeDataSource.read();
					}
				});
			});
		})();
	</script>
}